---
title: "Hands-on"
author: "Helena"
date: "28/10/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

http://leg.ufpr.br/~walmes/introds/

Git: https://github.com/HelenaDEspindula/Omega_Course_1.git
<<<<<<< HEAD

http://omegadatascience.com.br/downloads/instrucoes.html
=======
>>>>>>> d9842829a2a531f827dce1db759358ce988ef3ea

## Atalhos R

ctron + enter - avalia paragrafo
cntrol +shift + 0 - 4 telas
mouse na função + F1 - abre help da função
control + shift + c - comenta e descomenta
Alt + "-" - setinha de atribuição
control + shift + M - pipe
control +i - tab?

## Exemplo 1 - Futebol

```{r }

library(tidyverse)

library(readr)
packageVersion("readr")

# Caminho para o arquivo na WEB.

url <- "http://leg.ufpr.br/~walmes/data/euro_football_players.txt"

# Leitura com `readr`.
tb <- read_tsv(
  file = url,
  col_names = TRUE,
  quote = "",
  comment = "#"
)
class(tb)
str(tb, give.attr = FALSE)

#ncol(tb)
#nrom(tb)
dim(tb) ##dimensões

# 2. O nome das equipes.

#tb$team

unique(tb$team)

tb %>%
  distinct(team) # %>%
#print(n=Inf) %>%
#View()

tb_distin <- tb %>%
  distinct(team)
tb_distin

## tb %>% distinct(team)= distinct(tb, team)
## %>% = operador pipe

# 3. Total de jogadores por equipe.

tb %>%
  count(team, sort = TRUE)

# 4. Total de jogadores por país de origem.

tb %>%
  count(country, sort = TRUE)

# 5. Total de gols por equipe.
# 6. Total de cartões amarelos por equipe.
# 7. Total de cartões amarelos e vermelhos por equipe.

# tb %>%
#   count(, sort = TRUE)

names(tb)

tb %>%
  group_by(team) %>%
  summarise(
    goal = sum(goal, na.rm = TRUE),
    amarelos = sum(yel, na.rm = TRUE),
    vermelhos = sum(red, na.rm = TRUE)
  )

tb %>%
  group_by(team) %>%
  summarise_at(c("goal", "yel", "red"), sum, na.rm = TRUE)


tb %>%
  group_by(team) %>%
  summarise_at(c("goal", "yel", "red"), c("mean", "sd", "sum"), na.rm = TRUE)


tb %>%
  group_by(team) %>%
  summarise_if(is.numeric, c("mean", "sd", "sum"), na.rm = TRUE)


# summarise_all() - aplica em tudo

# 8. Substitua o NA dos cartões por 0.

#Verificar se todos os NA podem ser substituidos por 0!!!
a <- 0
b <- mean(tb$cm, na.rm = TRUE)
tb %>%
  replace_na(replace = list(
    goal = a,
    yel = 0,
    red = 0,
    cm = b,
    kg = 80
  )) %>%
  View()


tb %>%
  replace_na(replace = list(
    goal = a,
    yel = 0,
    red = 0,
    cm2 = mean(tb$cm, na.rm = TRUE),
    kg = 80
  )) %>%
  View()

find("replace_na")
find("group_by")
find("summarize")

# 9. Obtenha a média, médiana e desvio-padrão de (idade|altura|peso) por equipe.

tb %>%
  group_by(team) %>%
  summarise_at(c("cm", "kg", "age"), c("mean", "median", "sd"), na.rm = TRUE)

# 10. Determine a correlação entre peso e altura por equipe.

tb %>%
  group_by(team) %>%
  summarise(correlacao = cor(kg, cm, use = "pairwise.complete.obs")) #pear?

# 11. Determine o IMC médio por equipe.

# IMC = peso (kg) / (alt (m) )²

tb <- tb %>%
  mutate(imc = kg / (cm / 100) ^ 2)

View(tb)

tb %>%
  group_by(team) %>%
  summarise_at("imc", mean, na.rm = TRUE) %>%
  arrange(desc(imc))

tb %>%
  slice_max(order_by = imc, n = 10) %>%
  select(name, cm, kg, imc)

# 11.5 Crie a variável que represente a classe de obesidade pelo IMC.

lim <- c(0, 16.5, 18.5, 25, 30, 35, 40, Inf)

lab <- c("sev", "aba", "normal", "preobe", "obe1", "obe2", "obe3")

tb <- tb %>%
  mutate(imc_classe = cut(imc, breaks = lim, labels = lab))

tb %>%
  count(imc_classe)

tb %>%
  filter(imc_classe == "preobe") %>%
  select(name, kg, cm, imc, imc_classe, team) %>%
  count(team, sort = TRUE)




#View(tb2)

# 12. Calcule a proporção de disputas aéreas ganhas por faixa de altura com amplitura de classe de altura de 5 cm.

range(tb$cm, na.rm = TRUE)

lim <- seq(160, 210, by = 5)

tb <- tb %>%
  mutate(cm_classe = cut(cm, breaks = lim))

View(tb)

tb %>%
  select(aw)

tb %>%
  group_by(cm_classe) %>%
  summarise_at("aw", mean, na.rm = TRUE)

tb <- tb %>%
  mutate(cm_classe2 = cut(cm, breaks = lim, right = FALSE))

tb %>%
  group_by(cm_classe2) %>%
  summarise_at("aw", mean, na.rm = TRUE)

# 13. Crie a variável que representa a posição em campo do jogador.

tb %>%
  count(pos)

tb %>%
  mutate(position = str_sub(pos, 0, 1)) %>%
  count(position)

tb <- tb %>%
  mutate(position = str_replace(pos, "^([A-Z]+).*", "\\1"))

tb %>%
  count(position)

##REGEX


# 13. Tabela times x posição

tb %>%
  count(team, position) %>%
  pivot_wider(names_from = position, values_from = n)


tb %>%
  count(cm_classe, position) %>%
  pivot_wider(names_from = position, values_from = n)

```
## Aula 04 - Fundamentos de Estatística



```{r}
## Fundamentos de estatística: Ômega Fly ---------------------------------------
## Prof. Wagner Hugo Bonat · Ômega Data Science --------------------------------
## Data: 04/11/2021 ------------------------------------------------------------
rm(list=ls())

## Carregando alguns pacotes adicionais
library(readr) # Leitura de arquivos
library(dplyr) # Manipulação de dados
library(lubridate) # Manipulação de datas e horas
library(ggplot2) ## Gráficos

## Carregando a base de dados
#url <- "http://leg.ufpr.br/~wagner/data/omegafly.csv"
url <- "omegafly_mod.csv"
dados <- read_csv2(url, locale = locale(encoding = "ASCII")) #delimitador é ponto e virgula

str(dados)

## Dar uma olhada na base de dados
#View(dados)
head(dados)

## Calculando os atrasos

dados$hora_prevista_chegada2 <- hms(dados$hora_prevista_chegada, roll = TRUE )
dados$hora_chegada2 <- hms(dados$hora_chegada, roll = TRUE)

str(dados)

dados$atraso <- dados$hora_chegada2 - dados$hora_prevista_chegada2
dados$atraso <- as.numeric(dados$atraso)/60

## Olhando o resultado
#View(dados)
head(dados)

## Histograma
ggplot(dados) +
  geom_histogram(aes(atraso))

## Valores negativos, estranho? para o outro dia
dados %>%
  filter(atraso < -100) %>%
  View()

## Vamos somar 60*24 = 1440 minutes apenas nestes casos
dados <- dados %>%
  mutate(atraso = ifelse(atraso < -100, atraso + 1440, atraso))

## Distribuição de frequências
ggplot(dados) +
  geom_histogram(aes(atraso))

## Como se comporta a distribuição do atraso?
summary(dados$atraso)

## Dependendo do atraso a Omega Fly vai ter um custo
quantile(dados$atraso, probs = seq(0, 1, 0.05), na.rm = TRUE)

# A partir de quanto de atraso começamos a ter um custo?
# Vai depender da sua recomendação!

# Cenário 1: Atraso superior a uma hora vamos pagar
dados %>% 
  filter(atraso > 60) %>%
  count()

prop <- (887/dim(dados)[1])
prop

## Aproximadamente 7% das vendas teremos um custo com essa estratégia!
## Quanto vai custar? 

## Voltamos ao produto! 

# Remarcação custo 300
# Acomodação + custeio custo MÉDIO de 150.

# Suponha que vendemos 10000 passagens ao ano para este trajeto.
# Quanto esperamos pagar?
custo_total <- 450*(10000*prop)
custo_total

# Custo adicional por unidade (sem contar taxas de administração e lucro)
custo_add <- custo_total/10000
custo_add # Aproximadamente 31.25 adicional de preço!

# Parece razoável? Quais os problemas com essa abordagem?

# 1) Estamos olhando apenas para o passado.
# 2) Não sabemos entre todos os voos possíveis onde alocaremos os nossos clientes.
# 3) Estamos admitindo que o fato de atrasar para um cliente não tem associação com 
# o atraso de outros.
# 4) É esse mesmo o valor que vamos pagar? Não esse é apenas o valor esperado! 
# O que isso significa? Precisamos pensar em probabilidades.

## Voltamos para os slides

## Atribuindo pesos que refletem chances!
ggplot(dados) +
  geom_bar(aes(atraso))

# Agrupando em classes de 5 em 5 minutos
ggplot(dados) +
  geom_histogram(aes(atraso), binwidth = 5)

# Padronizando para que a soma abaixo da Figura seja 1
ggplot(dados) +
  geom_histogram(aes(atraso, y = ..density..), binwidth = 5)

# A área abaixo da Figura é uma probabilidade.

# Admitindo que a distribuição de frequências é uma boa representação da
# distribuição de probabilidade do tempo de atraso. 
# Podemos calcular probabilidades.

# Qual a probabilidade de um atraso ser superior a 60 minutos?
dados %>% 
  filter(atraso > 60) %>%
  count()

prob_60 <- 887/dim(dados)[1]
prob_60

# Agora temos a distribuição de probabilidade da qtd de tickets que vamos pagar
# Pago 0 se Y <= 60 e 1 se Y > 60

## Número de tickets que esperamos pagar
10000*prob_60

# Custo esperado de gasto em um ticket
0*(1-prob_60) + 450*prob_60

# Custo esperado em 10000 tickets
10000*(0*(1-prob_60) + 450*prob_60)

## Tudo estaria perfeito SE tivessemos realmente a "população"!!
## Mas o que é população? 

## Vamos voltar para os slides.

## Inferência estatística

## O que aconteceria se coletarmos apenas uma amostra de tamanho 10000?
set.seed(123) # Serve para tornar o resultado igual para todos
N <- dim(dados)[1]
n <- 10000
amostra <- sample(1:N, size = n, replace = TRUE)
dados_amostra <- dados[amostra,]

contagem <- dados_amostra %>% 
  filter(atraso > 60) %>%
  count()
prob_60 <- contagem$n/n
prob_60
# Custo esperado adicional por ticket
(0*(1-prob_60) + 450*prob_60)

# E se repetirmos muitas vezes!
n_rep <- 1000
custo_total <- c()
custo_ticket <- c()
prob_60 <- c()

for(i in 1:n_rep) {
  # Sorteia a amostra
  amostra <- sample(1:N, size = n, replace = TRUE)
  # Seleciona a amostra
  dados_amostra <- dados[amostra,]
  # Conta qts atrasos acima de 60 e estima a probabilidade
  prob_60[i] <- dim(dados_amostra[dados_amostra$atraso > 60,])[1]/n
  # Guardando os resultados
  custo_total[i] <- 10000*(0*(1-prob_60[i]) + 450*prob_60[i])
  custo_ticket[i] <- 450*prob_60[i]
}

## Distribuição de probabilidades da probabilidade de ter atraso maior do que 60
ggplot() +
  geom_histogram(aes(x = prob_60, y = ..density..), binwidth = 0.001)

## Distribuição de probabilidades do custo total
ggplot() +
  geom_histogram(aes(x = custo_total, y = ..density..))

## Distribuição de probabilidades do custo por ticket
ggplot() +
  geom_histogram(aes(x = custo_ticket, y = ..density..))


## Quantis
quantile(prob_60, probs = seq(0, 1, by = 0.05))
quantile(custo_total, probs = seq(0, 1, by = 0.05))
quantile(custo_ticket, probs = seq(0, 1, by = 0.05))

# Intervalo com 95% de confiança
quantile(prob_60, probs = c(0.025, 0.975))
quantile(custo_total, probs = c(0.025, 0.975))
quantile(custo_ticket, probs = c(0.025, 0.975))

## Voltamos para os slides.

## Por que um voo atrasa?

# Vamos começar investigando se o aeroporto de origem é importante.

# Opção 1
ggplot(dados) +
  geom_boxplot(aes(origin, atraso))

# Opção 2
ggplot(dados) +
  geom_histogram(aes(x = atraso, y = ..density.., fill = origin), 
                 alpha = 0.8, binwidth = 5)

# Opção 3
ggplot(dados) +
  geom_density(aes(x = atraso, fill = origin))

## Descritiva básica por grupo
dados %>%
  group_by(origin) %>%
  summarize("quantis" = quantile(atraso))

### Função para calcualar probabilidade
compute_probability <- function(y, corte) {
  mean(y > corte)
}

## Para uma particular amostra o que aconteceria?
set.seed(123) # Serve para tornar o resultado igual para todos
N <- dim(dados)[1]
n <- 10000
amostra <- sample(1:N, size = n, replace = TRUE)
dados_amostra <- dados[amostra,]

dados_amostra %>%
  group_by(origin) %>%
  summarize("quantis" = quantile(atraso))

dados_amostra %>%
  group_by(origin) %>%
  summarize("probabilidade" = compute_probability(atraso, corte = 60))

## Será que essa diferença é relevante a ponto de criar uma politica diferente
# de preço para cada aeroporto?

# E se repetirmos muitas vezes!
n_rep <- 1000
custo_total <- matrix(NA, ncol = 2, nrow = 1000)
custo_ticket <- matrix(NA, ncol = 2, nrow = 1000)
prob_60 <- matrix(NA, ncol = 2, nrow = 1000)
diferenca <- c()

for(i in 1:n_rep) {
  # Sorteia a amostra
  amostra <- sample(1:N, size = n, replace = TRUE)
  # Seleciona a amostra
  dados_amostra <- dados[amostra,]
  # Conta qts atrasos acima de 60 e estima a probabilidade
  probs <- dados_amostra %>%
    group_by(origin) %>%
    summarize("probabilidade" = compute_probability(atraso, corte = 60))
  prob_60[i,] <- probs$probabilidade
  diferenca[i] <- probs$probabilidade[1] - probs$probabilidade[2]
  # Guardando os resultados
  custo_total[i,] <- 10000*(0*(1-prob_60[i,]) + 450*prob_60[i,])
  custo_ticket[i,] <- 450*prob_60[i,]
}

## Resumo
quantile(prob_60[,1], probs = c(0.025, 0.975))
quantile(prob_60[,2], probs = c(0.025, 0.975))

quantile(custo_total[,1], probs = c(0.025, 0.975))
quantile(custo_total[,2], probs = c(0.025, 0.975))

quantile(custo_ticket[,1], probs = c(0.025, 0.975))
quantile(custo_ticket[,2], probs = c(0.025, 0.975))

quantile(diferenca, probs = c(0.025, 0.975))

dados_plot <- tibble("prob_60" = c(prob_60[,1], prob_60[,2]),
                     "total" = c(custo_total[,1], custo_total[,2]),
                     "ticket" = c(custo_ticket[,1], custo_ticket[,2]) ,
                     "aeroporto" = rep(c("EWR", "JFK"), each = 1000))

## Comparando as distribuições amostrais
ggplot(dados_plot) +
  geom_density(aes(x = prob_60, fill = aeroporto), alpha = 0.5)

## Distribuição da diferença
ggplot() +
  geom_density(aes(diferenca)) +
  geom_vline(xintercept = 0)

## Intervalo de confiança pra diferença
quantile(diferenca, probs = c(0.025, 0.975))

## Voltamos para os slides.

## Testes de hipóteses

## Hipótese nula: Não há diferença na probabilidade de atraso entre os aeroportos.
## Hipótese alternativa: Há diferença na probabilidade de atraso entre os aeroportos.

## Como fazer o teste?

# Simulamos da hipótese nula.
# Construímos a distribuição amostral sob a hipótese nula.
# Coletamos a nossa amostra.
# Se o observado for raro o suficiente rejeita H0 caso contrário não rejeitamos.

diferenca_H0 <- c()
for(i in 1:1000) {
  amostra <- sample(1:n, replace = TRUE)
  dados_amostra <- dados[amostra,]
  ## Criando os dados sob a hipótese nula
  dados_sob_h0 <- data.frame("atraso" = dados_amostra$atraso,
                             "Grupo_H0" = sample(c("EWR","JFK"), 
                                                 size = 10000, replace = TRUE))
  probs <- dados_sob_h0 %>%
    group_by(Grupo_H0) %>%
    summarize("probabilidade" = compute_probability(atraso, corte = 60))
  diferenca_H0[i] <- probs$probabilidade[1] - probs$probabilidade[2]
}

## Distribuição da diferença sob a hipótese nula
ggplot() +
  geom_density(aes(diferenca_H0)) +
  geom_vline(xintercept = 0)

# Seleciono a minha amostra
set.seed(123)
amostra <- sample(1:dim(dados)[1], size = 10000, replace = TRUE)

probs <- dados[amostra,] %>%
  group_by(origin) %>%
  summarize("probabilidade" = compute_probability(atraso, corte = 60))
dif_obs <- probs$probabilidade[1] - probs$probabilidade[2]

ggplot() +
  geom_density(aes(diferenca_H0)) +
  geom_vline(xintercept = 0) +
  geom_vline(xintercept = dif_obs)

## O que é o p-valor? Probabilidade de observar uma estatística amostral igual
# ou mais extrema do que a observada sob a hipótese nula.
# Se a hipotese é bilaterial (dierença) multiplica por dois
2*mean(diferenca_H0 < dif_obs)

# Regras do dedão p-valor < 0.05 rejeita H0. Da onde veio isso? Da cabeça de alguém!
# Pq? Só Deus sabe!!

## Leitura recomendada
# https://www.tandfonline.com/doi/full/10.1080/00031305.2016.1154108


## Como podemos facilitar o processo de avaliação diferente estratégias?
calcula_risco <- function(corte, n_vendas, custo_realoc, custo_acomo, dados) {
  custo_total <- c()
  custo_ticket <- c()
  prob <- c()
  N <- dim(dados)[1]
  custo <- custo_realoc + custo_acomo
  for(i in 1:n_rep) {
    # Sorteia a amostra
    amostra <- sample(1:N, size = n_vendas, replace = TRUE)
    # Seleciona a amostra
    dados_amostra <- dados[amostra,]
    # Conta qts atrasos acima de 60 e estima a probabilidade
    prob[i] <- dim(dados_amostra[dados_amostra$atraso > corte,])[1]/n_vendas
    # Guardando os resultados
    custo_total[i] <- n_vendas*(0*(1-prob[i]) + custo*prob[i])
    custo_ticket[i] <- custo*prob[i]
  }
  output <- data.frame("Probabilidade" = prob, 
                       "Total" = custo_total,
                       "Ticket" = custo_ticket)
  return(output)
}

## Estratégia 1: 60 minutos
avalia_60 <- calcula_risco(corte = 60, n_vendas = 10000, 
                           custo_realoc = 300, custo_acomo = 150,
                           dados = dados)

ggplot(avalia_60) +
  geom_density(aes(x = Probabilidade))
ggplot(avalia_60) +
  geom_density(aes(x = Ticket))

# E apenas 15 minutos, como ficaria o preço?
avalia_15 <- calcula_risco(corte = 15, n_vendas = 10000, 
                           custo_realoc = 300, custo_acomo = 150,
                           dados = dados)

ggplot(avalia_15) +
  geom_density(aes(x = Probabilidade))
ggplot(avalia_15) +
  geom_density(aes(x = Ticket))


## Talvez 45 minutos?
avalia_45 <- calcula_risco(corte = 45, n_vendas = 10000, 
                           custo_realoc = 300, custo_acomo = 150,
                           dados = dados)

ggplot(avalia_45) +
  geom_density(aes(x = Probabilidade))
ggplot(avalia_45) +
  geom_density(aes(x = Ticket))


## Podemos fazer para vários. 
# Suponha que a politica é ter 5% de risco ao ano.
## O interesse é no preço minimo do produto

corte <- seq(30, 90, by = 5)
custo <- c()
for(i in 1:length(corte)) {
  temp <- calcula_risco(corte = corte[i], n_vendas = 10000, 
                        custo_realoc = 300, custo_acomo = 150,
                        dados = dados)
  custo[i] <- quantile(temp$Ticket, 0.95)
  print(i)
}


## Quer cobrar qto? $ 25
grafico <- data.frame("corte" = corte, "custo" = custo)
ggplot(grafico) +
  geom_line(aes(corte, custo)) +
  geom_hline(yintercept = 25)

## FIM --------------------------
```


    




## Exemplo 2 - Carros



```{r }
## Fundamentos de estatística: Ômega Fly ---------------------------------------
## Prof. Wagner Hugo Bonat · Ômega Data Science --------------------------------
## Data: 09/11/2021 ------------------------------------------------------------
rm(list=ls())

## Carregando alguns pacotes adicionais
library(readr) # Leitura de arquivos
library(dplyr) # Manipulação de dados
library(lubridate) # Manipulação de datas e horas
library(ggplot2) ## Gráficos

## Carregando a base de dados
url <- "http://leg.ufpr.br/~wagner/data/omegafly.csv"
dados <- read_csv2(url)

## Dar uma olhada na base de dados
View(dados)

## Calculando os atrasos
dados$hora_prevista_chegada <- hm(dados$hora_prevista_chegada )
dados$hora_chegada <- hm(dados$hora_chegada)
dados$atraso <- dados$hora_chegada - dados$hora_prevista_chegada
dados$atraso <- as.numeric(dados$atraso)/60

## Olhando o resultado
View(dados)

## Histograma
ggplot(dados) +
  geom_histogram(aes(atraso))

## Valores negativos, estranho?
dados %>%
  filter(atraso < -100) %>%
  View()

## Vamos somar 60*24 = 1440 minutes apenas nestes casos
dados <- dados %>%
  mutate(atraso = ifelse(atraso < -100, atraso + 1440, atraso))

## Para facilitar a visualização vamos excluir atrasos acima de 500
dados <- dados %>% 
  mutate(atraso = ifelse(atraso > 500, NA, atraso))

## Distribuição de frequências
ggplot(dados) +
  geom_histogram(aes(atraso))

## Por que um voo atrasa?

## Aeroporto de origem ---------------------------------------------------------
ggplot(dados) +
  geom_density(aes(atraso, y = ..density.., fill = origin))

ggplot(dados) +
  geom_boxplot(aes(x = origin, y = atraso))

## Operadora do voo ------------------------------------------------------------
ggplot(dados) +
  geom_density(aes(atraso, y = ..density.., fill =carrier))

ggplot(dados) +
  geom_boxplot(aes(x = carrier, y = atraso))

ggplot(dados) +
  geom_boxplot(aes(x = carrier, y = atraso)) +
  facet_wrap(~ origin)

## Atraso médio por operadora e aeroporto de origem
dados %>%
  group_by(origin, carrier) %>%
  summarize("Media" = mean(atraso, na.rm = TRUE),
            "Desvio_padrao" = sd(atraso, na.rm = TRUE))

## Criando covariáveis baseado na data -----------------------------------------
dados$time_hour <- as.POSIXct(dados$time_hour, format = "%Y/%m/%d %H:%M")
dados <- dados %>%
  mutate(ano = year(time_hour),
         dia_semana = wday(time_hour, label = TRUE),
         dia_ano = yday(time_hour),
         dia_mes = mday(time_hour),
         mes = month(time_hour, label = TRUE), 
         dia = day(time_hour),
         hora = hour(time_hour),
         minuto = minute(time_hour), .)

dados$dia_semana <- factor(dados$dia_semana, levels = c("dom", "seg", "ter", 
                                                        "qua", "qui", "sex", "sáb"))
dados$mes <- factor(dados$mes, levels = c("jan", "fev", "mar", "abr", "mai", "jun",
                                          "jul", "ago", "set", "out", "nov", "dez"))

## Hora prevista da partida-----------------------------------------------------
ggplot(dados) +
  geom_boxplot(aes(x = as.factor(hora), y = atraso))

dados %>%
  group_by(hora) %>%
  summarize("Media" = mean(atraso, na.rm = TRUE),
            "Desvio_padrao" = sd(atraso, na.rm = TRUE))

## Dia da semana ---------------------------------------------------------------
ggplot(dados) +
  geom_boxplot(aes(x = dia_semana, y = atraso))

dados %>%
  group_by(dia_semana) %>%
  summarize("Media" = mean(atraso, na.rm = TRUE),
            "Desvio_padrao" = sd(atraso, na.rm = TRUE))

## Dia do mês ------------------------------------------------------------------
ggplot(dados) +
  geom_boxplot(aes(x = as.factor(dia_mes), y = atraso))

dados %>%
  group_by(dia_mes) %>%
  summarize("Media" = mean(atraso, na.rm = TRUE),
            "Desvio_padrao" = sd(atraso, na.rm = TRUE)) %>%
  View()

## Dia do ano ------------------------------------------------------------------
ggplot(dados) +
  geom_boxplot(aes(x = as.factor(dia_ano), y = atraso))

## Mes do ano ------------------------------------------------------------------
ggplot(dados) +
  geom_boxplot(aes(x = mes, y = atraso))

dados %>%
  group_by(mes) %>%
  summarize("Media" = mean(atraso, na.rm = TRUE),
            "Desvio_padrao" = sd(atraso, na.rm = TRUE))

## Voltar para os slides.

## Especificando um modelo simples para descrever os atrasos --------------------


## Acertando as categorias para mostrar na ordem natural
dados$dia_semana <- as.character(dados$dia_semana)
dados$dia_semana <- as.factor(dados$dia_semana)
dados$dia_semana <- factor(dados$dia_semana, levels = c("dom", "seg", "ter", 
                                                        "qua", "qui", "sex", "sáb"))

dados$mes <- as.character(dados$mes)
dados$mes <- as.factor(dados$mes)
dados$mes <- factor(dados$mes, levels = c("jan", "fev", "mar", "abr", "mai", "jun",
                                          "jul", "ago", "set", "out", "nov", "dez"))


## Regressão linear simples
# Efeito só da origem
fit1 <- lm(atraso ~ origin, data = dados)
summary(fit1)

## Regressão linear múltipla
# Efeito da operadorad
fit2 <- lm(atraso ~ carrier, data = dados)
summary(fit2)

## Hora do dia
fit3 <- lm(atraso ~as.factor(hora), data = dados)
summary(fit3)

## Dia da semana
fit4 <- lm(atraso ~ dia_semana, data = dados)
summary(fit4)

## Dia do mês
fit5 <- lm(atraso ~ as.factor(dia), data = dados)
summary(fit5)

## Mes do ano
fit6 <- lm(atraso ~ mes, data = dados)
summary(fit6)

## Dia do ano
fit7 <- lm(atraso ~ as.factor(dia_ano), data = dados)
summary(fit7)

## Juntando tudo!
fit_completo <- lm(atraso ~ origin + carrier +as.factor(hora) + 
                     dia_semana + mes, data = dados)
summary(fit_completo)

## E dia do ano e dia do mes? 
fit_completo2 <- lm(atraso ~ origin + carrier +as.factor(hora) + dia_semana + mes +
                     as.factor(dia_mes) + as.factor(dia_ano), data = dados)
summary(fit_completo2)

## Muitos parâmetros!! Superparametrização ???
anova(fit_completo2)

## Tem como simplificar?
require(mgcv)
fit_smooth <- gam(atraso ~ origin + carrier + as.factor(hora) + dia_semana + mes +
                   s(dia_mes) + s(dia_ano), data = dados)
summary(fit_smooth)
plot(fit_smooth)

## Podemos criar uma espécie de API em que entramos com as características do
# voo e a API solta o tempo esperado de atraso a incerteza associada. Podemos
# tbm calcular probabilidades de interesse, por exemplo, probabilidade de atrasar
# mais de 60 minutos.


################################################################################

## Regressão logística

# Vamos supor que queremos apenas calcular a probabilidade de atrasar mais de 60 minutos.
# Podemos criar uma nova variável resposta sendo: 0 se Y < 60 e 1 Y >= 60

dados <- dados %>%
  mutate(binaria = ifelse(atraso < 60, 0, 1))
prop.table(table(dados$binaria))


## Modelo completo
fit_logistico <- gam(binaria ~ origin + carrier + as.factor(hora) + 
                       dia_semana + mes + s(dia_mes) + s(dia_ano), 
                     family = binomial, data = dados)
summary(fit_logistico)

################################################################################

## Projeto: Detectando o genero baseado em características da voz

# Nome: Gender Recognition by Voice
# Tipo de resposta: Binária
# Modelo candidato: Regressão logística
# Endereço: Gender Recognition by Voice
# Arquivo: voice.csv
# Nível: Intermediário




```